# Global configuration
# -------------------------------------------------------------------------------------------------

sonar.host.url=https://sqcorporate.deltatre.com

# The project name
sonar.projectName=rogers-chromecast-receiver

# The project key (provided via on-boarding)
sonar.projectKey=rogers-chromecast-receiver

# Branches to keep when inactive
sonar.dbcleaner.branchesToKeepWhenInactive=main, develop

# Project configuration
# -------------------------------------------------------------------------------------------------

# Encoding format of source
sonar.sourceEncoding=UTF-8

# Path to directories containing source files
sonar.sources=src

# Path to test directories
# RWA tests are close to the tested modules so this variable should have the same values as sonar.sources
# sonar.tests=src

# Folder/files to exclude
sonar.exclusions=\
  node_modules,\
  dist,\

# sonar.test.inclusions=\
#   src/**/*.spec.ts,\
#   src/**/*.spec.tsx,\
#   build/**/*.spec.ts

# Exclude the following files from code coverage
# sonar.coverage.exclusions=\
#   /src/shared/service,\
#   /src/**/_test/

# TS config path
# sonar.typescript.tsconfigPath=tsconfig.json

# Reports
# -------------------------------------------------------------------------------------------------

# sonar.typescript.lcov.reportPaths=bin/reports/test/lcov.info
# sonar.testExecutionReportPaths=bin/reports/test/sonar-report.xml

# ESLint Report Files
# sonar.eslint.reportPaths=bin/reports/lint/eslint-report.json
